"""
Django settings for apphub project.

Generated by 'django-admin startproject' using Django 4.0.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

import os
from urllib.parse import urlparse
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('APPHUB_SETTINGS_SECRET_KEY', default='django-insecure-@&gp$u=3+j%te3+^d)4**8)csv5u^3u$(6g&$m8&t*ao61hc$e')
# gp$u=3+j%te3+
# **8)csv5u^3
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('APPHUB_SETTINGS_DEBUG_MODE', default=True)

EXTERNAL_WEB_URL = os.environ.get('APPHUB_SETTINGS_EXTERNAL_WEB_URL', default='')

EXTERNAL_API_URL = os.environ.get('APPHUB_SETTINGS_EXTERNAL_API_URL', default='')
if EXTERNAL_API_URL:
    ALLOWED_HOSTS = [urlparse(EXTERNAL_API_URL).hostname]
else:
    ALLOWED_HOSTS = []

API_URL_PREFIX = urlparse(EXTERNAL_API_URL).path
if API_URL_PREFIX and len(API_URL_PREFIX) > 0:
    API_URL_PREFIX = API_URL_PREFIX[1:]

# Application definition

INSTALLED_APPS = [
    'documentation.apps.DocumentationConfig',
    'user.apps.UserConfig',
    'organization.apps.OrganizationConfig',
    'application.apps.ApplicationConfig',
    'distribute.apps.DistributeConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'apphub.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'apphub.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES_ENGINE =  os.environ.get('APPHUB_SETTINGS_DEFAULT_SDATABASES_ENGINE', default='django.db.backends.sqlite3')
DATABASES = {
    'default': {
        'ENGINE': DATABASES_ENGINE,
    }
}
if DATABASES_ENGINE == 'django.db.backends.sqlite3':
    DATABASES['default']['NAME'] = os.environ.get('APPHUB_SETTINGS_DATABASE_NAME', default=BASE_DIR / 'db.sqlite3')
elif DATABASES_ENGINE == 'django.db.backends.mysql':
    DATABASES['default']['NAME'] = os.environ.get("APPHUB_SETTINGS_DATABASE_NAME")
    DATABASES['default']['HOST'] = os.environ.get("APPHUB_SETTINGS_DATABASE_HOST")
    DATABASES['default']['PORT'] = os.environ.get("APPHUB_SETTINGS_DATABASE_PORT")
    DATABASES['default']['USER'] = os.environ.get("APPHUB_SETTINGS_DATABASE_USER")
    DATABASES['default']['PASSWORD'] = os.environ.get("APPHUB_SETTINGS_DATABASE_PASSWORD")

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

DEFAULT_RENDERER_CLASSES = (
    'rest_framework.renderers.JSONRenderer',
)

if DEBUG:
    DEFAULT_RENDERER_CLASSES = DEFAULT_RENDERER_CLASSES + (
        'rest_framework.renderers.BrowsableAPIRenderer',
    )

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'user.authentication.BearerTokenAuthentication',
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_RENDERER_CLASSES': DEFAULT_RENDERER_CLASSES,
    'EXCEPTION_HANDLER': 'util.exception.custom_exception_handler'
}

# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

FONT_FILE = os.environ.get('APPHUB_SETTINGS_FONT_FILE', 'PingFang.ttc')

STATICFILES_STORAGE = os.environ.get('APPHUB_SETTINGS_STATICFILES_STORAGE', 'django.contrib.staticfiles.storage.StaticFilesStorage')
# DEFAULT_FILE_STORAGE = os.environ.get('APPHUB_SETTINGS_DEFAULT_FILE_STORAGE', 'django.core.files.storage.FileSystemStorage')
DEFAULT_FILE_STORAGE = os.environ.get('APPHUB_SETTINGS_DEFAULT_FILE_STORAGE', 'storage.NginxFileStorage.NginxPrivateFileStorage')


if STATICFILES_STORAGE == 'storage.AliyunOssStorage.AliyunOssStaticStorage' or DEFAULT_FILE_STORAGE == 'storage.AliyunOssStorage.AliyunOssMediaStorage':
    ALIYUN_OSS_ACCESS_KEY_ID = os.environ.get('ALIYUN_OSS_ACCESS_KEY_ID')
    ALIYUN_OSS_ACCESS_KEY_SECRET = os.environ.get('ALIYUN_OSS_ACCESS_KEY_SECRET')
    ALIYUN_OSS_BUCKET_NAME = os.environ.get('ALIYUN_OSS_BUCKET_NAME')
    ALIYUN_OSS_ENDPOINT =  os.environ.get('ALIYUN_OSS_ENDPOINT')
    ALIYUN_OSS_PUBLIC_URL =  os.environ.get('ALIYUN_OSS_PUBLIC_URL', ALIYUN_OSS_ENDPOINT)
    ALIYUN_OSS_KEY_PREFIX = os.environ.get('ALIYUN_OSS_KEY_PREFIX', '')
    ALIYUN_OSS_ROLE_ARN = os.environ.get('ALIYUN_OSS_ROLE_ARN')
    ALIYUN_OSS_REGION_ID = os.environ.get('ALIYUN_OSS_REGION_ID')


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/
STATIC_ROOT = os.environ.get('APPHUB_SETTINGS_STATIC_ROOT', default='var/static/')
STATIC_URL = os.environ.get('APPHUB_SETTINGS_STATIC_URL', default=EXTERNAL_WEB_URL + '/static/')

MEDIA_ROOT = os.environ.get('APPHUB_SETTINGS_MEDIA_ROOT', default='var/media/')
MEDIA_URL = os.environ.get('APPHUB_SETTINGS_MEDIA_URL', default=EXTERNAL_WEB_URL + '/media/')


# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# User
AUTH_USER_MODEL = "user.User"
AUTHENTICATION_BACKENDS = ["user.backends.EmailUsersModelBackend"]

CODE_EXPIRE_SECONDS = 2 * 60 * 60

SECURE_HSTS_SECONDS = 31536000
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SESSION_COOKIE_SECURE = True
SECURE_HSTS_PRELOAD = True
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
CSRF_COOKIE_SECURE = True
if EXTERNAL_WEB_URL.startswith('https://') and not DEBUG:
    SECURE_SSL_REDIRECT = True
