name: Zappa onto AWS Lambda + API Gateway

on:
  push:
    branches: [ zappa ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install Dependencies
      run: |
        python -m venv zappa-apphub && source zappa-apphub/bin/activate
        pip install -r requirements.txt
        pip install zappa
    - name: Configure AWS profile
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Zappa deployments
      run: zappa update dev
