name: Zappa onto AWS Lambda + API Gateway

on:
  push:
    branches: [ zappa ]

jobs:
  build:

    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install zappa
    - name: Configure AWS profile
      run: |
        aws configure set region us-east-1 --profile default
        aws configure set output json --profile default
        aws configure set aws_access_key_id ${{ secrets.PRIMARY_AWS_ACCESS_KEY_ID }} --profile default
        aws configure set aws_secret_access_key ${{ secrets.PRIMARY_AWS_SECRET_ACCESS_KEY }} --profile default
    - name: Zappa deployments
      run: zappa update dev
