name: Zappa deploy

on:
  push:
    branches: [ zappa ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Dependencies
      run: |
        wget https://raw.githubusercontent.com/FlipperPA/django-s3-sqlite/master/shared-objects/python-3-8/_sqlite3.so
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install
        pipenv install zappa
    - name: Configure AWS profile
      run: |
        pipenv run aws configure set region us-east-1 --profile default
        pipenv run aws configure set output json --profile default
        pipenv run aws configure set aws_access_key_id ${{ secrets.PRIMARY_AWS_ACCESS_KEY_ID }} --profile default
        pipenv run aws configure set aws_secret_access_key ${{ secrets.PRIMARY_AWS_SECRET_ACCESS_KEY }} --profile default
    - name: Zappa deployments
      run: |
        pipenv run python manage.py migrate
        pipenv run zappa update dev
